= Versioned Fields

`VersionedFields` gem was created to help you
gracefully modify data in you columns without downtime.
It allows you to migrate fields only when the appropriate record is accessed.

== Usage

=== Before the start

To make the gem work you need to create a column called `yourfield_version`.
For example, if you have a `foo` column, you need to create a column called `foo_version`.

Propagate it with default value, lets say - `1`. Example of Rails migration:

```ruby
class CreateFooVersion < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :foo_version, :integer, default: 1, null: false
  end
end
```

=== Using VersionedFields migrations

Assuming you have `users` table with field `address`, and `address_version`.

On version 1 (initial version) we have addresses like `Green Avenue, #1516`.

On version 2 we want to append city to it: `Los Angeles, Green Avenue, #1516`.

Let's write a migration. Create `db/migrate_versioned_fields/user/address.rb` file,
and put there the following code:

```ruby
# db/migrate_versioned_fields/user/address.rb

VersionedFields::Migration.draw_for(User, :address) do
  version 1 # No block, since it's a first version
  version 2 do |prev_value|
    # Write here code needed to migrate from v1 to v2
    # You can you model methods here
    "Los Angeles #{prev_value}"
  end
end
```

Now, restart your server.
When you access a certain user (i.e. - `User.find(22)`), it's `address` value
will be automatically upgraded to version 2, with the city name.

Now let's assume you decided to replace city with state. Open migration file for `address` field,
and add a new migration:

```diff
# db/migrate_versioned_fields/user/address.rb

VersionedFields::Migration.draw_for(User, :address) do
  version 1
  version 2 do |prev_value|
    "Los Angeles #{prev_value}"
  end

+ version 3 do |value|
+   value.gsub('Los Angeles', 'LA')
+ end
end
```

You may write a background job which will migrate users slowly while server is running.
It is as simple as:

```ruby
# lib/tasks/migrate_with_zero_downtime.rake

namespace :users do
  task zero_downtime_migration: :environment do
    # Load every user one by one and update address
    User.find_each
  end
end
```

== Future TODO:

- Write tests
- Support for Sequel
